parameters:
  - name: response
    optional: false

action_groups:
  - actions:
      - type: set-variables
        scripting_type: spel
        variables:
          - name: user_reply
            value: <? response ?>

  - condition: (user_reply == "yup")
    actions:
      - type: message
        message:
          type: text
          content: "Your requirements can be effectively implemented as a BAdI Extension. \n\nFor the first requirement, a BAdI extension is already available, which can be found [here](http://www.a.com)."
          markdown: true
          
  - condition: (user_reply == "nope")
    actions:
      - type: message
        message:
          type: text
          content: "You said no."
